

function PrivacyPolicy() {
    return (
      <div className="max-w-[1340px] py-[80px] w-[90%] mx-auto space-y-[30px]">
        <div>
            <h3 className="font-miniature 2xl:text-[92.21px] xl:text-[92.21px] lg:text-[92.21px] md:text-[92.21px] sm:text-[52.21px] text-[52.21px] font-[400] leading-[110%]">Privacy Policy</h3>
        </div>
        <div>
            <p className="2xl:text-[18px] xltext-[18px] lg:text-[18px] md:text-[18px] sm:text-[14px] text-[14px] font-[500]">Welcome to https://www.thecaregroup.ca/ (the "Site"). We understand that privacy online is important to users of our Site, especially when conducting business. This statement governs our privacy policies with respect to those users of the Site ("Visitors") who visit without transacting business and Visitors who register to transact business on the Site and make use of the various services offered by The Care Group of Companies (collectively, "Services") ("Authorized Customers").</p> <br />
            <p className="2xl:text-[18px] xltext-[18px] lg:text-[18px] md:text-[18px] sm:text-[14px] text-[14px] font-[500]">
            ​ "Personally Identifiable Information" refers to any information that identifies or can be used to identify, contact, or locate the person to whom such information pertains, including, but not limited to, name, address, phone number, fax number, email address, financial profiles, social security number, and credit card information. Personally Identifiable Information does not include information that is collected anonymously (that is, without identification of the individual user) or demographic information not connected to an identified individual
            </p> <br />
            <p  className="2xl:text-[18px] xltext-[18px] lg:text-[18px] md:text-[18px] sm:text-[14px] text-[14px] font-[500]">What Personally Identifiable Information is collected?</p> <br />
            
            <p  className="2xl:text-[18px] xltext-[18px] lg:text-[18px] md:text-[18px] sm:text-[14px] text-[14px] font-[500]">We may collect basic user profile information from all of our Visitors. We collect the following additional information from our Authorized Customers: the names, addresses, phone numbers, and email addresses of Authorized Customers, the nature and size of the business, and the nature and size of the advertising inventory that the Authorized Customer intends to purchase or sell.</p> <br />
            <p className="2xl:text-[18px] xltext-[18px] lg:text-[18px] md:text-[18px] sm:text-[14px] text-[14px] font-[500]">What organizations are collecting the information?</p> <br />
            <p className="2xl:text-[18px] xltext-[18px] lg:text-[18px] md:text-[18px] sm:text-[14px] text-[14px] font-[500]">In addition to our direct collection of information, our third party service vendors (such as credit card companies, clearinghouses, and banks) who may provide such services as credit, insurance, and escrow services may collect this information from our Visitors and Authorized Customers. We do not control how these third parties use such information, but we do ask them to disclose how they use personal information provided to them by Visitors and Authorized Customers. Some of these third parties may be intermediaries that act solely as links in the distribution chain, and do not store, retain, or use the information given to them.</p><br />
            <p className="2xl:text-[18px] xltext-[18px] lg:text-[18px] md:text-[18px] sm:text-[14px] text-[14px] font-[500]">How does the Site use Personally Identifiable Information?</p><br />
            <p className="2xl:text-[18px] xltext-[18px] lg:text-[18px] md:text-[18px] sm:text-[14px] text-[14px] font-[500]">We use Personally Identifiable Information to customize the Site, to make appropriate service offerings, and to fulfill buying and selling requests on the Site. We may email Visitors and Authorized Customers about research or purchase and selling opportunities on the Site or information related to the subject matter of the Site. We may also use Personally Identifiable Information to contact Visitors and Authorized Customers in response to specific inquiries, or to provide requested information.</p><br />
            <p className="2xl:text-[18px] xltext-[18px] lg:text-[18px] md:text-[18px] sm:text-[14px] text-[14px] font-[500]">With whom may the information be shared?</p><br />
            <p className="2xl:text-[18px] xltext-[18px] lg:text-[18px] md:text-[18px] sm:text-[14px] text-[14px] font-[500]">Personally Identifiable Information about Authorized Customers may be shared with other Authorized Customers who wish to evaluate potential transactions with other Authorized Customers. We may share aggregated information about our Visitors, including the demographics of our Visitors and Authorized Customers, with our affiliated agencies and third party vendors. We also offer the opportunity to "opt-out" of receiving information or being contacted by us or by any agency acting on our behalf.</p><br />
            <p className="2xl:text-[18px] xltext-[18px] lg:text-[18px] md:text-[18px] sm:text-[14px] text-[14px] font-[500]">How is Personally Identifiable Information stored?</p><br />
            <p className="2xl:text-[18px] xltext-[18px] lg:text-[18px] md:text-[18px] sm:text-[14px] text-[14px] font-[500]">Personally Identifiable Information collected by The Care Group of Companies is securely stored and is not accessible to third parties or employees of The Care Group of Companies except for use as indicated above.</p><br />
            <p className="2xl:text-[18px] xltext-[18px] lg:text-[18px] md:text-[18px] sm:text-[14px] text-[14px] font-[500]">What choices are available to Visitors regarding the collection, use, and distribution of the information?</p><br />
            <p className="2xl:text-[18px] xltext-[18px] lg:text-[18px] md:text-[18px] sm:text-[14px] text-[14px] font-[500]" >Visitors and Authorized Customers may opt out of receiving unsolicited information from or being contacted by us and/or our vendors and affiliated agencies by responding to emails as instructed, or by contacting us at</p><br />
            <p className="2xl:text-[18px] xltext-[18px] lg:text-[18px] md:text-[18px] sm:text-[14px] text-[14px] font-[500]">Cookies</p><br />
            <p className="2xl:text-[18px] xltext-[18px] lg:text-[18px] md:text-[18px] sm:text-[14px] text-[14px] font-[500]">A cookie is a string of information that a website stores on a visitor’s computer, and that the visitor’s browser provides to the website each time the visitor returns.</p><br />
            <p className="2xl:text-[18px] xltext-[18px] lg:text-[18px] md:text-[18px] sm:text-[14px] text-[14px] font-[500]">Are cookies used on the site?</p><br />
            <p className="2xl:text-[18px] xltext-[18px] lg:text-[18px] md:text-[18px] sm:text-[14px] text-[14px] font-[500]">Cookies are used for a variety of reasons. We use Cookies to obtain information about the preferences of our Visitors and the services they select. We also use Cookies for security purposes to protect our Authorized Customers. For example, if an Authorized Customer is logged on and the site is unused for more than 10 minutes, we will automatically log the Authorized Customer off. Visitors who do not wish to have cookies placed on their computers should set their browsers to refuse cookies before using https://www.thecaregroup.ca/, with the drawback that certain features of website may not function properly without the aid of cookies</p><br />
            <p className="2xl:text-[18px] xltext-[18px] lg:text-[18px] md:text-[18px] sm:text-[14px] text-[14px] font-[500]">Cookies used by our service providers</p><br />
            <p className="2xl:text-[18px] xltext-[18px] lg:text-[18px] md:text-[18px] sm:text-[14px] text-[14px] font-[500]">Our service providers use cookies and those cookies may be stored on your computer when you visit our website. You can find more details about which cookies are used in our cookies info page.</p><br />
            <p className="2xl:text-[18px] xltext-[18px] lg:text-[18px] md:text-[18px] sm:text-[14px] text-[14px] font-[500]">How does The Care Group use login information?</p><br />
            <p className="2xl:text-[18px] xltext-[18px] lg:text-[18px] md:text-[18px] sm:text-[14px] text-[14px] font-[500]">The Care Group of Companies uses login information, including, but not limited to, IP addresses, ISPs, and browser types, to analyze trends, administer the Site, track a user's movement and use, and gather broad demographic information.</p><br />
            <p className="2xl:text-[18px] xltext-[18px] lg:text-[18px] md:text-[18px] sm:text-[14px] text-[14px] font-[500]">What partners or service providers have access to Personally Identifiable Information from Visitors and/or Authorized Customers on the Site?</p><br />
            <p className="2xl:text-[18px] xltext-[18px] lg:text-[18px] md:text-[18px] sm:text-[14px] text-[14px] font-[500]">The Care Group of Companies has entered into and will continue to enter into partnerships and other affiliations with a number of vendors. Such vendors may have access to certain Personally Identifiable Information on a need to know the basis for evaluating Authorized Customers for service eligibility. Our privacy policy does not cover their collection or use of this information. Disclosure of Personally Identifiable Information to comply with the law. We will disclose Personally Identifiable Information in order to comply with a court order or subpoena or a request from a law enforcement agency to release information. We will also disclose Personally Identifiable Information when reasonably necessary to protect the safety of our Visitors and Authorized Customers.</p> <br />
            <p className="2xl:text-[18px] xltext-[18px] lg:text-[18px] md:text-[18px] sm:text-[14px] text-[14px] font-[500]">How does the site keep Personally Identifiable Information secure?</p><br />
            <p className="2xl:text-[18px] xltext-[18px] lg:text-[18px] md:text-[18px] sm:text-[14px] text-[14px] font-[500]">All of our employees are familiar with our security policy and practices. The Personally Identifiable Information of our Visitors and Authorized Customers is only accessible to a limited number of qualified employees who are given a password in order to gain access to the information. We audit our security systems and processes on a regular basis. Sensitive information, such as credit card numbers or social security numbers, is protected by encryption protocols, in place to protect information sent over the Internet. While we take commercially reasonable measures to maintain a secure site, electronic communications, and databases are subject to errors, tampering, and break-ins, and we cannot guarantee or warrant that such events will not take place and we will not be liable to Visitors or Authorized Customers for any such occurrences</p><br />
            <p className="2xl:text-[18px] xltext-[18px] lg:text-[18px] md:text-[18px] sm:text-[14px] text-[14px] font-[500]">We provide Visitors and Authorized Customers with a mechanism to delete/deactivate Personally Identifiable Information from the Site's database by contacting them. However, because of backups and records of deletions, it may be impossible to delete a Visitor's entry without retaining some residual information. An individual who requests to have Personally Identifiable Information deactivated will have this information functionally deleted, and we will not sell, transfer, or use Personally Identifiable Information relating to that individual in any way moving forward.</p><br />
            <p className="2xl:text-[18px] xltext-[18px] lg:text-[18px] md:text-[18px] sm:text-[14px] text-[14px] font-[500]">Your rights</p><br />
            <p className="2xl:text-[18px] xltext-[18px] lg:text-[18px] md:text-[18px] sm:text-[14px] text-[14px] font-[500]">These are summarized rights that you have under the data protection law</p><br />
            <p className="2xl:text-[18px] xltext-[18px] lg:text-[18px] md:text-[18px] sm:text-[14px] text-[14px] font-[500]">
            1 - The right to access<br />2 - The right to rectification<br />3 - The right to erasure<br />4 - The right to restrict processing<br />5 - The right to object to processing<br />6 - The right to data portability<br />7 - The right to complain to a supervisory authority<br />8 - The right to withdraw consent
            </p><br />
            <p className="2xl:text-[18px] xltext-[18px] lg:text-[18px] md:text-[18px] sm:text-[14px] text-[14px] font-[500]">What happens if the Privacy Policy changes?</p><br />
            <p className="2xl:text-[18px] xltext-[18px] lg:text-[18px] md:text-[18px] sm:text-[14px] text-[14px] font-[500]">We will let our Visitors and Authorized Customers know about changes to our privacy policy by posting such changes on the Site. However, if we are changing our privacy policy in a manner that might cause disclosure of Personally Identifiable Information that a Visitor or Authorized Customer has previously requested not be disclosed, we will contact such Visitor or Authorized Customer to allow such Visitor or Authorized Customer to prevent such disclosure.</p><br />
            <p className="2xl:text-[18px] xltext-[18px] lg:text-[18px] md:text-[18px] sm:text-[14px] text-[14px] font-[500]">Links</p><br />
            <p className="2xl:text-[18px] xltext-[18px] lg:text-[18px] md:text-[18px] sm:text-[14px] text-[14px] font-[500]">https://www.thecaregroup.ca/ contains links to other websites. Please note that when you click on one of these links, you are moving to another website. We encourage you to read the privacy statements of these linked sites as their privacy policies may differ ours. Contact our Privacy Officer for any questions.</p>
        </div>
      </div>
    );
  }
  
  export default PrivacyPolicy;
  