// import { Geist, Geist_Mono } from "next/font/google";
import NavbarMobile from "@/components/Mobile/NavbarMobile";
import "./globals.css";
import Navbar from "@/components/Desktop/Navbar";
import Footer from "@/components/Desktop/Footer";
import FooterMobile from "@/components/Mobile/FooterMobile";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        {/* Desktop */}
        <div className="max-lg:hidden"><Navbar /></div>
        {/* Mobile */}
        <div className="lg:hidden"><NavbarMobile /></div>

        {children}
        
        {/* Desktop */}
        <div className="max-lg:hidden"><Footer /></div>
        {/* Mobile */}
        <div className="lg:hidden"><FooterMobile /></div>
      </body>
    </html>
  );
}
